export const dummyStudents = [
  {
    id: 1,
    name: "Alex Johnson",
    role: "Computer Science",
    university: "State University",
    batch: "2024",
    semester: "4th Semester",
    image: "https://i.pravatar.cc/150?u=1",
  },
  {
    id: 2,
    name: "Sarah Williams",
    role: "Information Technology",
    university: "Tech Institute",
    batch: "2025",
    semester: "2nd Semester",
    image: "https://i.pravatar.cc/150?u=2",
  },
  {
    id: 3,
    name: "Michael Brown",
    role: "Data Science",
    university: "State University",
    batch: "2024",
    semester: "4th Semester",
    image: "https://i.pravatar.cc/150?u=3",
  },
  {
    id: 4,
    name: "Emma Davis",
    role: "Computer Science",
    university: "Tech Institute",
    batch: "2024",
    semester: "4th Semester",
    image: "https://i.pravatar.cc/150?u=4",
  },
  {
    id: 5,
    name: "James Wilson",
    role: "Software Engineering",
    university: "Global Tech",
    batch: "2023",
    semester: "6th Semester",
    image: "https://i.pravatar.cc/150?u=5",
  },
  {
    id: 6,
    name: "Olivia Miller",
    role: "Computer Science",
    university: "State University",
    batch: "2025",
    semester: "2nd Semester",
    image: "https://i.pravatar.cc/150?u=6",
  },
  {
    id: 7,
    name: "William Taylor",
    role: "Information Technology",
    university: "Global Tech",
    batch: "2024",
    semester: "4th Semester",
    image: "https://i.pravatar.cc/150?u=7",
  },
  {
    id: 8,
    name: "Sophia Martinez",
    role: "Data Science",
    university: "State University",
    batch: "2023",
    semester: "6th Semester",
    image: "https://i.pravatar.cc/150?u=8",
  },
];
